### PR TITLE
Rack v2 compatibility

### LINKED ISSUE #7: res/ComponentLibrary/LEDButton.svg does not exist on Rack v2
Hi.
Trying out your modules in v2, just noticed the code from your module is trying to load the file `res/ComponentLibrary/LEDButton.svg` but this does not exist on v2.

### PR DESCRIPTION
**Pull request by falkTX**
This makes it work without crashes for me.
I imported the v1 LEDButton.svg from v1 source code, so the modules keep working as-is. A little license note is added to make it clear where this file comes from.

Fixes #7

### CODE REVIEW

**Comment by mgunyho** [comment]
Hi, thank you very much for the bug report and PR! I will look into this in more detail a bit later this week, and try to get the whole v2 thing done.

I guess it's okay to use the v1 artwork because of the CC lisence, but doesn't the v2 API / SDK include some similar default LED/LED button?

**Comment by mgunyho** [comment]
Woah, I didn't even realize I had the Delay.svg from VCV in the res folder, I don't know how it ended up there :sweat_smile:  I guess I used it as a reference and committed it by accident.

**Comment by falkTX** [comment]
> I guess it's okay to use the v1 artwork because of the CC lisence, but doesn't the v2 API / SDK include some similar default LED/LED button?

I dont know actually, the core and fundamental panels were reworked, so random things have changed.
Best to ask in the forums or email support.

**Comment by mgunyho** [comment]
I created #9 with some commits from this one, but not using the LED button SVG. Can you please check if that works?

**Pull request closed without merging**
