### PR TITLE
v2: LEDButton fix

### LINKED ISSUE #7: res/ComponentLibrary/LEDButton.svg does not exist on Rack v2
Hi.
Trying out your modules in v2, just noticed the code from your module is trying to load the file `res/ComponentLibrary/LEDButton.svg` but this does not exist on v2.

### PR DESCRIPTION
**Pull request by mgunyho**
- Remove ToggleLEDButton, use `VCVLightLatch` instead, like for example VCV LFO 
- Remove VCV v1 artwork that was accidentally committed a long time ago

@falkTX, can you check if compiles for you and works without crashing? And also, do you get any deprecation warnings when compiling? Apparently `SVGSwitch` is deprecated in favor of `SvgSwitch`, but I didn't see any warnings about it for some reason (even when manually adding `-Wdeprecated-declarations` to compile flags), I just accidentally saw it in the headers.

Thanks again for the original PR!

Supersedes #8, fixes #7.

### CODE REVIEW

**Comment by falkTX** [comment]
Seems to work as far as I can tell

Screenshot_20211222_231615

**Comment by noodleboy91** [comment]
> Seems to work as far as I can tell
> 
> Screenshot_20211222_231615

How did you get the black panels?

**Comment by falkTX** [comment]
oh dont mind them, I invert some of the colors at runtime, so that I do not need to modify any files on disk.
personally quite like the outcome.

Screenshot_20211223_023950

**Comment by mgunyho** [comment]
Cool, thanks!

**Comment by noodleboy91** [comment]
> oh dont mind them, I invert some of the colors at runtime, so that I do not need to modify any files on disk. personally quite like the outcome.
> 
> Screenshot_20211223_023950

Oh wow, I really like that. I am not sure how I would go aobut doing it on my computer, but it looks great :)

**Comment by falkTX** [comment]
Well I already did the work for the dark mode stuff, it is all part of https://github.com/DISTRHO/Cardinal

**Pull request merged**
