### PR TITLE
PulseGenerator: Adds longer gate time and reset gate options.

### PR DESCRIPTION
**Pull request by EnigmaCurry**
Hi there! I use your modules all the time, thanks so much!

I had the desire for PulseGenerator to have a longer gate time, so I modified it to allow up to a 10 minute length. The original 10s length is still a good default range, so I made an optional config setting in the right click context menu to change modes: `Longer gate time (up to 10 mins)` . I also added a `Reset Gate` menu item (because 10 mins is a long time to wait to reset on its own). Because there is a bit more state now, I also added an `onReset` callback to handle initialization properly.

### CODE REVIEW

**Comment by mgunyho** [comment]
Hi! I'm happy to hear that you like the modules!

Thanks for the feature suggestion and PR. However, this feels like quite an obscure feature to be honest. How often do you need a 10-minute-long gate? For something this specific that is rarely needed, I think it's acceptable if it is a bit inconvenient and needs multiple modules. Here's an example of a 600-second long gate built using a one-second gate, a counter module (in this case [PdArray ministep](https://library.vcvrack.com/PdArray/Ministep)) and some logic:

rack-10min-gate

The basic idea is to take the AND of the "finish" trigger of the 1-second gate and the output of the comparison "counter output > 0", and feed that back into the increment of the counter. The output of the A>B comparison is the gate, and the counter maximum value is the length of the gate in seconds. The gate can be reset by sending a trigger to the RST input of the counter.

**Comment by EnigmaCurry** [comment]
Thats very cool, and your point is well taken. In my case I was triggering a sampler with a long sample. I have been building some of my own modules that abstract some of the common things I do, it saves space and declutters the details. I wish I could collapse several modules down into something I no longer need to look at. In VCV this is not an option, but I can make my own modules. So I totally accept you not taking this PR, I just wanted to share, and I will continue to use this in my patches or may make another of my own modules based on this. Thanks very much for the LICNESE. Cheers.

**Comment by mgunyho** [comment]
Hmm, wouldn't in that case a trigger-based sample player be better? At least the samplers from the cf module can be played using a trigger if I recall correctly.

**Comment by EnigmaCurry** [comment]
I was using Bidoo Canard, which indeed has both gate and trigger inputs. However, I almost always prefer a gate over a trigger. A trigger is ambiguous and can descynchronize from the meaning that I intended. A gate is unambiguously ON or OFF the way I intend. Thanks again for your input.

**Pull request closed without merging**
